read.csv(file="Effect of alcohol consumption on college life.csv")
?read.csv
age <-c(1, 3, 5, 2, 11, 9, 3, 9, 12, 13)
dim(age)
weight<-c(4.4, 5.3, 7.2, 5.2,  8.5, 7.3, 6.0, 10.4, 10.2, 6.1)
length(weight)
dim(age, weight)
infant <-data.frame(age, weight)
dim(infant)
names(infant)
length(age)
length(weight)
dim(infant)
names(infant)
class(infant)

sd(age)
sd(weight)
cor(age, weight)
plot(age, weight)
abline(age, weight)
lm(age ~ weight, data = infant)
plot(age ~ weight, data = infant)
fir<-lm(age ~ weight, data = infnat)
abline(fit)
write.csv(infant,"/Users/ilan/R/2020.03.27/infant.csv")
inf<-read.csv("/Users/ilan/R/2020.03.27/infant.csv")
